### ISSUE TITLE
Output file description

### ISSUE THREAD

**Issue by nandobonf** [CompMeth/VSeq-Toolkit#4]
Dear Authors,
Is it possible to have a description of each column in the "ISGenomeVector.csv" output file?
I reckon the "SequenceCount" column indicate the number of reads supporting the event. 
Are discordant and split reads treated the same way?
Thanks.

**Comment by CompMeth** [comment]
Hi, 

1) About columns in the "ISGenomeVector.csv"  file;
Most of the columns are self-explanatory (for example Chr, GenomicPosition, StrandGenomic, VectorName, VectorPosition, StrandVector, ReadID, Sequence, SpanGenomic, SpanVector). 
The explanation of other columns; 
Feature1_Genomic - it depicts if the mapping region is uniquely or multiple mapped in the genome based on the threshold specified in the configuration file. 
Similarly, Feature2_Vector - indicates if the mapping region is uniquely or multiple mapped in the vector reference based on the threshold specified in the configuration file.
IdentityPercGenomic - it is the mapping identity percentage of genome mapped region.
IdentityPercVector - it is the identity percentage of vector mapped region 
OverlapFusion - the analysis strategy depends on finding a fusion between vector and genome mapped regions of the read. This column indicates how many bases at the fusion site were overlapped between genomic and vector mapped regions.
DistanceFusion - similarly it indicates if there were any bases at the fusion site between vector and genome that were not mapped.
SequenceCount - indicates the number of clustered reads for that particular position based on the clustering range specified in the configuration file.
The rest of the columns (RefSeqID, GeneStrand, GeneName, GeneLength, DisttoTSS, Upstream, Downstream, IntronExon) are related to the annotation of the genomic position based on refSeq table obtained form UCSC, as mentioned in the related toolkit manual and configuration file.

2) Regarding question about spilt and discordant reads;
The analysis strategy for fusion analysis in mode 2 and 3 of toolkit depends basically on identifying and processing all those reads, where one read of the pair at least have some mapped region (with genome or vector) and some soft-clipped region. The soft-clip part that is the unmapped region in the same read is then processed to check if it has mapping somewhere in the genome or vector. The stringency parameter in configuration file controls the selection of paired-end reads based on the sam flag information of their correctness of mapping. Please also see the published article of toolkit for workflow and details.
