### ISSUE TITLE
Is there a typo in the 

### ISSUE THREAD

**Issue by npatel-ah** [CompMeth/VSeq-Toolkit#7]
Hello, 

I was using the tool to detect vector insertion in the host and while reviewing the script I came across a line which might be a bug. See at line 80 [vecGenIS.sh](https://raw.githubusercontent.com/CompMeth/VSeq-Toolkit/master/scripts/vecGenIS.sh)

```
78 cat $outDir/alignment.4.sam  |  cut -f15 | cut -d ';' -f1 | paste $outDir/alignment.4.sam - | cut -f1-14,16  | awk '{print $0";"}' > $outDir/alignment.4.sam.temp00
79 cut -f15  $outDir/alignment.4.sam.temp00|  awk '{print gsub (/;/, "")}' | paste $outDir/alignment.4.sam.temp00 - | awk '($16>=2)' | cut -f1 | grep -v -Fwf - $outDir/alignment.4.sam.temp00 > $outDir/alignment.4.sam.temp1
80 mv $outDir/alignment.4.sam.temp00 $outDir/alignment.4.sam

```

I didn't see any other reference for "alignment.4.sam.temp1"  Would you please confirm if the line 80 should be 

mv $outDir/alignment.4.sam.**temp1** $outDir/alignment.4.sam

**Comment by CompMeth** [comment]
Hi, 
It is indeed not a bug, but this was an intermediate file generated for some internal checks during dev. However, this does not effect current version and you do not need to perform any change/modification. You can ignore it.
